// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD25SHEdW2XCw_zFExbcw6DzfOoYMXIEpI',
    appId: '1:605675947890:web:576159997fd8fa97a7ffeb',
    messagingSenderId: '605675947890',
    projectId: 'medxpert-9a26f',
    authDomain: 'medxpert-9a26f.firebaseapp.com',
    storageBucket: 'medxpert-9a26f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDixocQ48YAwoJN1idCpS2KMFMtMZ6hMys',
    appId: '1:605675947890:android:3602c87d263e6986a7ffeb',
    messagingSenderId: '605675947890',
    projectId: 'medxpert-9a26f',
    storageBucket: 'medxpert-9a26f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZfv_s-dIDYNYU3IRf3GZt5bVLn-xCj8',
    appId: '1:605675947890:ios:a6704cf9cba5bf34a7ffeb',
    messagingSenderId: '605675947890',
    projectId: 'medxpert-9a26f',
    storageBucket: 'medxpert-9a26f.firebasestorage.app',
    iosBundleId: 'com.example.medxpert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUZfv_s-dIDYNYU3IRf3GZt5bVLn-xCj8',
    appId: '1:605675947890:ios:a6704cf9cba5bf34a7ffeb',
    messagingSenderId: '605675947890',
    projectId: 'medxpert-9a26f',
    storageBucket: 'medxpert-9a26f.firebasestorage.app',
    iosBundleId: 'com.example.medxpert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD25SHEdW2XCw_zFExbcw6DzfOoYMXIEpI',
    appId: '1:605675947890:web:f09d8e9cf32b1e0ea7ffeb',
    messagingSenderId: '605675947890',
    projectId: 'medxpert-9a26f',
    authDomain: 'medxpert-9a26f.firebaseapp.com',
    storageBucket: 'medxpert-9a26f.firebasestorage.app',
  );
}
